### PR TITLE
fix Release build of liveSDK for desktop

### PR DESCRIPTION
**Pull request by jayongg**
Release build did not work because a define was not set.  Set the define.

See line 31. I don't know why git thinks there were 221 deletions and 221 additions.

### CODE REVIEW

**Comment by peternied** [comment]
Typically that is due to changes in line endings, would you mind changing that around and squashing those changes together?

**Comment by jayongg** [comment]
Sorry – what did you want me to do?

 

Would you want me to change the linefeeds such that they are unix-style and re-request?

**Comment by peternied** [comment]
I've manually merged this change in, thanks for your contribution

**Comment by jayongg** [comment]
Thanks!






Sent from Windows Mail





From: Peter Nied
Sent: ‎Sunday‎, ‎May‎ ‎10‎, ‎2015 ‎9‎:‎21‎ ‎PM
To: 'liveservices/LiveSDK-for-Windows'
Cc: Jay Ongg2001





I've manually merged this change in, thanks for your contribution

**Pull request closed without merging**
